### ISSUE TITLE
I get an error when I try to run "make"

### ISSUE THREAD

**Issue by Natanielsr** [baerwolf/USBaspLoader#21]
i try to run typing "make" in console but i receive this error
.
.
======>BUILDING BOOTLOADER FIRMWARE
.
make[1]: Entering directory `D:/Nataniel/Documents/custom keyboard/discipline/bootloader/USBaspLoader-master/firmware'
main.c: In function 'leaveBootloader':
main.c:322: warning: 'noreturn' function does return
c:/winavr-20100110/bin/../lib/gcc/avr/4.3.3/../../../../avr/bin/ld.exe: address 0x2002 of main.elf section .text is not within region text
c:/winavr-20100110/bin/../lib/gcc/avr/4.3.3/../../../../avr/bin/ld.exe: address 0x2002 of main.elf section .text is not within region text
make[1]: *** [main.elf] Error 1
make[1]: Leaving directory `D:/Nataniel/Documents/custom keyboard/discipline/bootloader/USBaspLoader-master/firmware'
make: *** [do_firmware] Error 2

**Comment by thonyek** [comment]
what avr microcontroller are you using?

The linker throws you an error because your compilation code does not fit inside your microcontroller memory.
Or this might be a compiler-specific issue. I don't use WinAvr.

**Comment by Natanielsr** [comment]
Im trying to burn a bootloader to The atmega32a microcontroller

**Comment by thonyek** [comment]
I don't use WinAVR since it is kinda outdated and gets my environment PATH variable overridden. So I don't know much about it. 

But I can provide you with an alternate solution to compile this and get a binary file. I assume you use Windows 10.
Step 1: Install ubuntu on your windows by following this [link](https://ubuntu.com/tutorials/ubuntu-on-windows#1-overview)
Step 2: Open ubuntu and in the terminal type
`sudo apt update && sudo upgrade`
Step 3: Install the git to pull stuff from github. In the terminal type
`sudo apt install git`
Step 4: Install the toolchain. In the terminal type
`sudo apt install gcc-avr avr-libc`
Step 5: Change current directory to your C drive. 
`cd /mnt/c`
Step 6: Clone this repository to your c drive.
`git clone https://github.com/baerwolf/USBaspLoader.git`
Step 7: Change directory to USBaspLoader.
`cd USBaspLoader/`
Step 8: Compile the source code
`make clean && make all`

The binary will be in the updater folder

**Comment by Natanielsr** [comment]
Ty i will try

**Comment by baerwolf** [comment]
Totally forgot about this issue - I assume it is resolved now...
...so I will close it.
